# Generated by Django 3.0.8 on 2020-08-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='city',
            new_name='location',
        ),
    ]
