# Generated by Django 3.0.8 on 2020-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20200813_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
